### ISSUE TITLE
Streamlit example: port number do not match between README>Quickstart and what is printed in the terminal

### ISSUE THREAD

**Issue by akhalighi** [enthought/edge-examples#54]
From [readme](https://github.com/enthought/edge-examples/blob/main/Streamlit/README.md):

> Run the Docker image via python -m ci run. The app will serve on http://127.0.0.1:8888/ in a local development mode.

But after running the image I see this in the terminal:
 
```
You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:9000
```

**Comment by akhalighi** [comment]
The "rerouting" is happening by the native base image as explained in the [startup script](https://github.com/enthought/edge-examples/blob/main/Streamlit/src/startup-script.sh):

> This file will be automatically picked up by the edge-native-base machinery, which runs a small proxy server in front of your app.  Your app must bind to 127.0.0.1 on port 9000 for this to work.  The container itself will serve on port 8888, through the proxy.

**Comment by andrewcollette** [comment]
Unfortunately that message comes from Streamlit itself, and there doesn't seem to be any way to shut it off.

**Comment by akhalighi** [comment]
Yup. Let's just update the readme to let users know that the port they see printed in the console might be different from where they can actually need to go to get access to their app.
