### ISSUE TITLE
Where `get_config()` is defined. 

### ISSUE THREAD

**Issue by dwillhelm** [enthought/edge-examples#61]
In case anyone else was wondering where this `get_config()` was defined. Might save somebody an hour or two. 

https://github.com/enthought/edge-examples/blob/952c7efc309f3d2c7465893c3e92cba73249741b/Panel/ci/jupyterhub_config.py#L50

Online: 
* https://ipython.org/ipython-doc/dev/config/intro.html
* https://github.com/ipython/traitlets/blob/c5c9166373041dd561d8ad86e8990ae844d26306/traitlets/config/loader.py#L483-L501
* https://stackoverflow.com/questions/32102059/jupyterhub-where-is-get-config-defined-and-how-do-i-create-a-custom-authenticat

**Comment by andrewcollette** [comment]
Hi @dwillhelm!  Can you explain some more why you needed to find the get_config() definition?

**Comment by dwillhelm** [comment]
I was debugging, and I wasn't sure if this was causing the bug. Ultimately, it wasn't the source of the bug, but it was confusing enough that I spent some considerable time figuring out where that function came from and how it was used. TBF, I don't work with Jupyterhub servers a lot so maybe this would seem normal to others. 

Feel free to remove this issues if you need to avoid open issues. 

Maybe a comment in the code might be enough to avoid possible confusion.

**Comment by andrewcollette** [comment]
Thanks!
