### ISSUE TITLE
`minimal` example highlights a problem with gunicorn imports

### ISSUE THREAD

**Issue by EdwinWiseOne** [enthought/edge-examples#72]
The `minimal` example fails to pass the preflight checks.  It was passing the morning of 7 March 2024  and starting failing that afternoon, across several PRs.

Looking at the error logs, the `gunicorn` utils is importing `pkg_resources`:

```
Starting app
Traceback (most recent call last):
  File "/home/app/.edm/envs/edm/bin/gunicorn", line 8, in <module>
    from gunicorn.app.wsgiapp import run
  File "/home/app/.edm/envs/edm/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/home/app/.edm/envs/edm/lib/python3.8/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/home/app/.edm/envs/edm/lib/python3.8/site-packages/gunicorn/util.py", line 26, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Apparently  `pkg_resources` was deprecated (see https://github.com/benoitc/gunicorn/issues/2840), and, apparently, now missing.

What’s weird is that minimal isn’t the only example that uses gunicorn but it’s the only one failing, but that may only be a temporary situation.

We may need to address what version of gunicorn we are using.

**Comment by carlosdtrejo** [comment]
The `pkg_resource` in `setuptools` is marked as deprecated now (see [setuptools](https://setuptools.pypa.io/en/latest/pkg_resources.html)).

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

`gunicorn` introduced a fix in version "21.0.0" (see https://github.com/benoitc/gunicorn/pull/2963). However, the latest version currently provided by EDM is "20.0.4-2".

To resolve the issue effectively, it would be necessary to upgrade the `gunicorn` package to version "21.0.0" or higher.

**Comment by EdwinWiseOne** [comment]
@carlosdtrejo What's weird is that only the one example shows the problem, but don't we use gunicorn in several others?  But I'm not surprised that we need an update.

**Comment by carlosdtrejo** [comment]
That's right. I see that "Plotly Dash" and "React" examples use it. I'll have to investigate further but I believe we need an update either way.

**Comment by carlosdtrejo** [comment]
I also noticed that both [React](https://github.com/enthought/edge-examples/blob/main/React/ci/__main__.py#L34) and [Plotly Dash](https://github.com/enthought/edge-examples/blob/main/Plotly%20Dash/ci/__main__.py#L34) Examples add `setuptools` as a dependency when building the Docker image. Compared to `Minimal` Example which just adds "flask", "gunicorn" and "enthought_edge" as dependencies.

The Preflight test passes if we add `setuptools` to the Minimal app [dependencies](https://github.com/enthought/edge-examples/blob/main/Minimal/ci/__main__.py#L28).
